In [1]:
import tensorflow as tf


In [2]:
model = tf.keras.Sequential()
model.add(tf.keras.layers.InputLayer(input_shape=(8,), name='Input_layer'))
model.add(tf.keras.layers.Dense(4, activation='relu',
                                name='First_hidden_layer'))
model.add(tf.keras.layers.Dense(1, name='Output_layer'))
model.variables

[<tf.Variable 'First_hidden_layer/kernel:0' shape=(8, 4) dtype=float32, numpy=
 array([[ 0.6981918 ,  0.5149048 , -0.61951536, -0.2558007 ],
        [-0.298075  , -0.31148812, -0.24136388, -0.6915394 ],
        [-0.40002617, -0.05711168,  0.09753454, -0.34964064],
        [-0.5396447 , -0.5153315 ,  0.21898139, -0.19443756],
        [ 0.18794024,  0.08118159, -0.41570684, -0.10516804],
        [ 0.2337429 , -0.1901654 ,  0.05054772, -0.38975552],
        [ 0.24747837, -0.1466884 , -0.28332478,  0.40429217],
        [-0.6672409 , -0.5026099 ,  0.17465419, -0.4423349 ]],
       dtype=float32)>,
 <tf.Variable 'First_hidden_layer/bias:0' shape=(4,) dtype=float32, numpy=array([0., 0., 0., 0.], dtype=float32)>,
 <tf.Variable 'Output_layer/kernel:0' shape=(4, 1) dtype=float32, numpy=
 array([[0.08352673],
        [0.2583784 ],
        [0.1366167 ],
        [0.9388976 ]], dtype=float32)>,
 <tf.Variable 'Output_layer/bias:0' shape=(1,) dtype=float32, numpy=array([0.], dtype=float32)>]

In [4]:
data = tf.random.normal((32,8))
print(data)

tf.Tensor(
[[ 0.6368344   0.43920338 -0.22080734 -0.55608326  0.00695442 -1.999286
  -0.89584917 -0.3710475 ]
 [ 1.8844335   0.34563273  0.47174475  0.25796443 -0.0454198   1.2678024
   0.823285   -0.21600601]
 [-0.41526943 -0.951413    2.0352921  -0.59163207 -0.02498497 -1.0397755
   0.8191223   0.807868  ]
 [-0.70179194  0.08942103 -2.358343    0.54590493  0.96300745  0.5561305
   0.2624593  -1.1950905 ]
 [ 0.16720942 -0.563293    1.8472568  -1.1219355   0.6893605  -1.0515136
   0.679081   -0.7821387 ]
 [ 1.4630352   0.7465147  -0.23727481  0.5133703  -1.1369729   0.43224794
  -0.47680587 -0.9848904 ]
 [-0.28417626 -0.10131839 -0.05835356 -0.36469918  0.670736    0.8623177
  -0.30300167 -1.359542  ]
 [-0.78395915  0.7960772  -0.33629957 -0.455074    0.86048436  1.3480055
  -2.752534   -0.21451627]
 [-0.71112865  0.7186964   1.2123039  -0.07054644  0.16784614  0.71235156
   0.57043725  0.07922249]
 [ 0.55875146  1.528996   -0.15344304  0.9681924  -1.568419    0.12532179
   0.08746027 

In [5]:
prediction = model.predict(data)
print(prediction)

1/1 [==============================] - 0s 94ms/step
[[0.6099439 ]
 [0.2421777 ]
 [0.5734689 ]
 [1.191422  ]
 [1.2155174 ]
 [0.2577412 ]
 [0.568312  ]
 [0.08386915]
 [0.02572922]
 [0.        ]
 [0.2769717 ]
 [0.13051628]
 [0.51194745]
 [1.1031364 ]
 [0.44043761]
 [0.02462095]
 [0.2539761 ]
 [1.6717304 ]
 [1.7723963 ]
 [0.5714669 ]
 [0.29821798]
 [0.14774674]
 [0.53237313]
 [0.03444014]
 [0.22549537]
 [0.04829049]
 [1.1849413 ]
 [0.25836167]
 [0.27334914]
 [0.99838114]
 [0.13259439]
 [0.01701194]]
