In [1]:
import tensorflow as tf


In [2]:
df = tf.data.experimental.make_csv_dataset('drugsComTrain_raw.tsv',
                                           batch_size=1, field_delim='\t')


In [3]:
def prep_ds(ds, shuffle_buffer_size=1024, batch_size=32):
    # shuffle the dataset
    df = ds.shuffle(buffer_size=shuffle_buffer_size)
    # repeat the dataset
    ds = ds.repeat()
    # batch the dataset
    ds = ds.batch(batch_size)
    return ds


In [4]:
ds = prep_ds(df, batch_size=5)

In [5]:
for x in ds.take(1):
    print(x)

OrderedDict([('', <tf.Tensor: shape=(5, 1), dtype=int32, numpy=
array([[179192],
       [103308],
       [  6418],
       [114953],
       [171984]])>), ('drugName', <tf.Tensor: shape=(5, 1), dtype=string, numpy=
array([[b'Olanzapine'],
       [b'Celecoxib'],
       [b'Ocella'],
       [b'Diazepam'],
       [b'Meloxicam']], dtype=object)>), ('condition', <tf.Tensor: shape=(5, 1), dtype=string, numpy=
array([[b'Schizoaffective Disorde'],
       [b'Osteoarthritis'],
       [b'Birth Control'],
       [b'Anxiety'],
       [b'ibromyalgia']], dtype=object)>), ('review', <tf.Tensor: shape=(5, 1), dtype=string, numpy=
array([[b'"I have used this medication for around two years. It Is very good with helping Schizoid Type Thoughts however i would not recommend the medication as a long term medication due to weight gain and its ability to affect whether or not you can wake up in the morning. It has a tendency to make me fall asleep for two days straight. \r\r\n\r\r\nFrom - Adult Male who has had 

In [6]:
import tensorflow_hub as hub
embedding = "https://tfhub.dev/google/tf2-preview/gnews-swivel-20dim/1"
hub_layer = hub.KerasLayer(embedding, input_shape=[], dtype=tf.string, trainable=True)


In [7]:
for x in ds.take(1):
    print(hub_layer(tf.reshape(x['review'], [-1])))

tf.Tensor(
[[ 4.7236526e-01 -3.7830012e+00  7.5368166e-01  1.3165244e+00
  -2.6019814e+00 -4.5250230e+00 -2.8416398e+00  1.3278745e+00
   3.2640491e+00  2.2648478e-01 -1.8199880e+00  2.3640738e+00
   5.9722906e-01  1.1873682e+00 -5.4386458e+00  3.6466916e+00
   3.5637581e+00 -4.3614302e+00 -2.6346319e+00 -1.2079631e+00]
 [-2.6543397e-01 -1.6079483e+00 -4.5786725e-05  2.8694639e-01
  -4.5297688e-01 -4.7150311e+00 -3.5185704e+00 -7.2849977e-01
  -2.5209707e-01 -1.5049562e+00 -1.4764192e+00  3.7190340e+00
   1.5046980e+00 -1.4262709e-01 -3.1497161e+00  2.6290543e+00
   1.8439178e+00 -2.8899231e+00 -2.6620418e-01 -7.5190341e-01]
 [ 1.2163694e+00 -1.3188944e+00  1.2792206e+00  6.8698460e-01
  -9.3437180e-02 -2.7210875e+00 -1.6216682e+00  1.4645144e+00
   1.0519783e+00 -1.0184649e+00  3.7752774e-01  1.6924906e+00
   4.9311638e-01 -4.6826359e-02 -1.5866463e+00  1.2172081e+00
   1.7213893e+00 -1.6909559e+00 -6.9943830e-02 -1.3531902e+00]
 [ 6.8641776e-01 -1.8642155e+00 -6.0622171e-02  1.531463