In [2]:
import tensorflow as tf

In [3]:
tf.__version__

'2.10.1'

In [5]:
tensor1 = tf.Variable([1,2,3], dtype=tf.int32, name='my_tensor', trainable=True)
tensor1.shape

TensorShape([3])

In [6]:
tf.rank(tensor1)

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [21]:
int_variable = tf.Variable(4113, tf.int16)
int_variable
tf.rank(int_variable)
tf.rank(int_variable).numpy()
int_variable.shape
int_variable.shape.as_list()
vector_variable = tf.Variable([0.23, 0.42, 0.35], tf.float32)
vector_variable
tf.rank(vector_variable).numpy()
vector_variable.shape.as_list()
matrix_variable = tf.Variable([[4113, 7511, 6259], [3870, 6725, 6962]], tf.int32)
matrix_variable
tf.rank(matrix_variable).numpy()
matrix_variable.shape.as_list()
tensor_variable = tf.Variable([[[4113, 7511, 6259],
                                [3870, 6725, 6962]],
                               [[5102, 7038, 6591],
                                [3661, 5901, 6235]],
                               [[951, 1208, 1098],
                                [870, 645, 948]]])
tensor_variable
tf.rank(tensor_variable).numpy()
tensor_variable.shape.as_list()



[3, 2, 3]

In [25]:
int1 = tf.Variable(4113, tf.int32)
int2 = tf.Variable(7511, tf.int32)
int3 = tf.Variable(6529, tf.int32)
int_sum = int1+int2+int3
int_sum.numpy()


18153

In [30]:
vec1 = tf.Variable([4113, 3870, 5102], tf.int32)
vec2 = tf.Variable([7511, 6725, 7038], tf.int32)
vec3 = tf.Variable([6529, 6962, 6591], tf.int32)
vec_sum = vec3+vec2+vec1
print(vec_sum.numpy())
#vec_sum
print((vec1[0] + vec2[0] + vec3[0]).numpy())
print((vec1[1] + vec2[1] + vec3[1]).numpy())
print((vec1[2] + vec2[2] + vec3[2]).numpy())

[18153 17557 18731]
18153
17557
18731


In [33]:
matrix1 = tf.Variable([[4113, 3870, 5102],
                       [3611, 951, 870]], tf.int32)
matrix2 = tf.Variable([[7511, 6725, 7038],
                       [5901, 1208, 645]], tf.int32)
matrix3 = tf.Variable([[6529, 6962, 6591],
                       [6235, 1098, 948]], tf.int32)
matrix1.shape == matrix2.shape == matrix3.shape
matrix_sum = matrix3+matrix2+matrix1
matrix_sum.numpy()


array([[18153, 17557, 18731],
       [15747,  3257,  2463]])

In [35]:
tensor1 = tf.Variable([1,2,3,4,5,6])
print(tensor1)
tensor_reshape = tf.reshape(tensor1, shape=[3,2])
tensor_reshape

<tf.Variable 'Variable:0' shape=(6,) dtype=int32, numpy=array([1, 2, 3, 4, 5, 6])>


<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]])>

In [37]:
tensor1 = tf.Variable([1,2,3,4,5,6])
print(tensor1.numpy())
tensor_transpose = tf.transpose(tensor1)
tensor_transpose.numpy()

[1 2 3 4 5 6]


array([1, 2, 3, 4, 5, 6])

In [38]:
matrix1 = tf.Variable([[1,2,3,4], [5,6,7,8]])
matrix1.shape.as_list()

[2, 4]

In [39]:
reshape1 = tf.reshape(matrix1, shape=[4,2])
reshape1

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])>

In [40]:
reshape1.shape.as_list()

[4, 2]

In [41]:
reshape2 = tf.reshape(matrix1, shape=[1,8])
reshape2

<tf.Tensor: shape=(1, 8), dtype=int32, numpy=array([[1, 2, 3, 4, 5, 6, 7, 8]])>

In [42]:
reshape2.shape.as_list()

[1, 8]

In [43]:
reshape3 = tf.reshape(matrix1, shape=[8, 1])
reshape3

<tf.Tensor: shape=(8, 1), dtype=int32, numpy=
array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])>

In [44]:
reshape3.shape.as_list()

[8, 1]

In [45]:
reshape4 = tf.reshape(matrix1, shape=[2,2,2])
reshape4

<tf.Tensor: shape=(2, 2, 2), dtype=int32, numpy=
array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])>

In [46]:
reshape4.shape.as_list()

[2, 2, 2]

In [47]:
tf.rank(reshape4).numpy()

3

In [48]:
transpose1 = tf.transpose(matrix1)
transpose1

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])>

In [49]:
transpose1 == reshape1

<tf.Tensor: shape=(4, 2), dtype=bool, numpy=
array([[ True, False],
       [False, False],
       [False, False],
       [False,  True]])>

In [50]:
transpose2 = tf.transpose(reshape4)
transpose2

<tf.Tensor: shape=(2, 2, 2), dtype=int32, numpy=
array([[[1, 5],
        [3, 7]],

       [[2, 6],
        [4, 8]]])>

In [51]:
tensor1 = tf.Variable([[1,2,3]])
tensor2 = tf.Variable([[1], [2], [3]])
tensor_mult = tf.matmul(tensor1, tensor2)
tensor_mult

<tf.Tensor: shape=(1, 1), dtype=int32, numpy=array([[14]])>

In [52]:
tensor_mult = tensor1 @ tensor2
tensor_mult

<tf.Tensor: shape=(1, 1), dtype=int32, numpy=array([[14]])>

In [53]:
tensor1 = tf.Variable([[1,2,3]])
scalar_mult = 5 * tensor1
scalar_mult

<tf.Tensor: shape=(1, 3), dtype=int32, numpy=array([[ 5, 10, 15]])>

In [54]:
matrix1 = tf.Variable([[1.0,0.0,3.0,1.0,2.0],
                       [0.0,1.0,1.0,1.0,1.0],
                       [2.0,1.0,0.0,2.0,0.0]], tf.float32)
matrix1

<tf.Variable 'Variable:0' shape=(3, 5) dtype=float32, numpy=
array([[1., 0., 3., 1., 2.],
       [0., 1., 1., 1., 1.],
       [2., 1., 0., 2., 0.]], dtype=float32)>

In [55]:
matrix1.shape.as_list()

[3, 5]

In [56]:
matrix2 = tf.Variable([[0.49, 103],
                       [0.18, 38],
                       [0.24, 69],
                       [1.02, 75],
                       [0.68, 78]])
matrix2

<tf.Variable 'Variable:0' shape=(5, 2) dtype=float32, numpy=
array([[  0.49, 103.  ],
       [  0.18,  38.  ],
       [  0.24,  69.  ],
       [  1.02,  75.  ],
       [  0.68,  78.  ]], dtype=float32)>

In [57]:
matmul1 = tf.matmul(matrix1, matrix2)
matmul1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[  3.5900002, 541.       ],
       [  2.1200001, 260.       ],
       [  3.2      , 394.       ]], dtype=float32)>

In [58]:
matrix3 = tf.Variable([[120.0, 100.0, 90.0],
                       [30.0, 15.0, 20.0],
                       [220.0, 240.0, 185.0],
                       [145.0, 160.0, 155.0],
                       [330.0, 295.0, 290.0]])
matrix3

<tf.Variable 'Variable:0' shape=(5, 3) dtype=float32, numpy=
array([[120., 100.,  90.],
       [ 30.,  15.,  20.],
       [220., 240., 185.],
       [145., 160., 155.],
       [330., 295., 290.]], dtype=float32)>

In [60]:
matmul3 = matrix3 @ matmul1
matmul3

<tf.Tensor: shape=(5, 2), dtype=float32, numpy=
array([[9.3080005e+02, 1.2638000e+05],
       [2.0350000e+02, 2.8010000e+04],
       [1.8906001e+03, 2.5431000e+05],
       [1.3557500e+03, 1.8111500e+05],
       [2.7381001e+03, 3.6949000e+05]], dtype=float32)>

In [61]:
# activity 1.0.3 - applying activation functions
# 3x4 tensor shows sales from various sales reps
# rows are sales reps
# columns are vehicles available
# values are average percentage difference from msrp
# values can be positive or negative based on the price they could get for the car
# 3 reps, 4 types of cars
input1 = tf.Variable([[-0.013, 0.024, 0.06, 0.022],
                      [0.001, -0.047, 0.039, 0.016],
                      [0.018, 0.030, -0.021, -0.028]], tf.float32)
input1


<tf.Variable 'Variable:0' shape=(3, 4) dtype=float32, numpy=
array([[-0.013,  0.024,  0.06 ,  0.022],
       [ 0.001, -0.047,  0.039,  0.016],
       [ 0.018,  0.03 , -0.021, -0.028]], dtype=float32)>

In [65]:
# weights represents the msrp of the cars, a 4x1 tensor
weights = tf.Variable([[19995.95], [24995.50],
                       [36745.50], [29995.95]],
                      tf.float32)
# bias is a 3x1 representing the fixed costs associated with each salesperson
bias = tf.Variable([[-2500.0], [-2500.0], [-2500.0]], tf.float32)
# matrix multiply the input by the weight to show the average deviation from the msrp on all cars
# also add the bias to subtract the fixed costs of each salesperson
output = tf.matmul(input1,weights) + bias
print(output)
# or do these separately to see if they can get the same value
op1 = tf.matmul(input1,weights)
print(op1)
op2 = op1 + bias
print(op2)
# so it is the same, while the second rep started positive, the -2500 bias turns them negative
output = tf.keras.activations.relu(output)
print(output)
# relu activation zeros any negative values, so only positive remain (the first rep)

tf.Tensor(
[[  704.58545]
 [-1741.7827 ]
 [-3001.75   ]], shape=(3, 1), dtype=float32)
tf.Tensor(
[[3204.5854 ]
 [ 758.2173 ]
 [-501.75006]], shape=(3, 1), dtype=float32)
tf.Tensor(
[[  704.58545]
 [-1741.7827 ]
 [-3001.75   ]], shape=(3, 1), dtype=float32)
tf.Tensor(
[[704.58545]
 [  0.     ]
 [  0.     ]], shape=(3, 1), dtype=float32)
